apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-nginx
  name: dev-my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
      run: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
        run: my-nginx
    spec:
      containers:
      - image: nginx
        name: my-nginx
        ports:
        - containerPort: 80
