{
 "title": "my-first-java-online-app-jvm",
 "description": "jvm dashboard, complicate with multi-pod env && add avg metrics. reference: https://grafana.com/grafana/afashboards/4701-jvm-micrometer/",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "应用环境", "query": "prometheus" },
   { "name": "pod_name", "label": "pod", "query": { "query": "label_values(pod_name)" } },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": {
     "query": "label_values(jvm_buffer_memory_used_bytes{pod_name=~\"[[pod_name]]\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_uptime_seconds{pod_name=~\"[[pod_name]]\"})",
     "legendFormat": "{{pod_name}}  min"
    },
    {
     "expr": "max(process_uptime_seconds{pod_name=~\"[[pod_name]]\"})",
     "legendFormat": "{{pod_name}}  max"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_start_time_seconds{pod_name=~\"[[pod_name]]\"}*1000)",
     "legendFormat": "{{pod_name}}  min "
    },
    {
     "expr": "max(process_start_time_seconds{pod_name=~\"[[pod_name]]\"}*1000)",
     "legendFormat": "{{pod_name}} max"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\", area=\"heap\"})",
     "legendFormat": "{{pod_name}}  "
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\", area=\"nonheap\"})",
     "legendFormat": "{{pod_name}}  "
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collections (AVG)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_count{pod_name=~\"[[pod_name]]\"}[1m])) by (action, cause)",
       "legendFormat": "{{pod_name}}  {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations (AVG)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{pod_name=~\"[[pod_name]]\"}[1m])) by (action, cause) / on (action, cause) (sum(rate(jvm_gc_pause_seconds_count{pod_name=~\"[[pod_name]]\"}[1m])) by (action, cause))",
       "legendFormat": "{{pod_name}}  avg {{action}} ({{cause}})"
      },
      {
       "expr": "avg(jvm_gc_pause_seconds_max{pod_name=~\"[[pod_name]]\"})",
       "legendFormat": "{{pod_name}}  max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted (AVG)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(rate(jvm_gc_memory_allocated_bytes_total{pod_name=~\"[[pod_name]]\"}[1m]))",
       "legendFormat": "{{pod_name}}  allocated"
      },
      {
       "expr": "avg(rate(jvm_gc_memory_promoted_bytes_total{pod_name=~\"[[pod_name]]\"}[1m]))",
       "legendFormat": "{{pod_name}}  promoted"
      }
     ]
    },
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{pod_name=~\"[[pod_name]]\"}[1m])",
       "legendFormat": "{{pod_name}}  {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{pod_name=~\"[[pod_name]]\"}[1m])/rate(jvm_gc_pause_seconds_count{pod_name=~\"[[pod_name]]\"}[1m])",
       "legendFormat": "{{pod_name}}  avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{pod_name=~\"[[pod_name]]\"}[1m])",
       "legendFormat": "{{pod_name}}  allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{pod_name=~\"[[pod_name]]\"}[1m])",
       "legendFormat": "{{pod_name}}  promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_heap (AVG)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "{{pod_name}}  used"
    },
    {
     "expr": "avg(jvm_memory_committed_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "{{pod_name}}  commited"
    },
    {
     "expr": "avg(jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "{{pod_name}}  max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "{{pod_name}}  used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "{{pod_name}}  commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "{{pod_name}}  max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap (AVG)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_nonheap\"})",
       "legendFormat": "{{pod_name}}  used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_nonheap\"})",
       "legendFormat": "{{pod_name}}  commited"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_nonheap\"})",
       "legendFormat": "{{pod_name}}  max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{pod_name}}  used"
      },
      {
       "expr": "jvm_memory_committed_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{pod_name}}  commited"
      },
      {
       "expr": "jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "{{pod_name}}  max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM Heap (AVG)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", area=\"heap\"})",
       "legendFormat": "{{pod_name}}  used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{pod_name=~\"[[pod_name]]\", area=\"heap\"})",
       "legendFormat": "{{pod_name}}  committed"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\", area=\"heap\"})",
       "legendFormat": "{{pod_name}}  max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap (AVG)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", area=\"nonheap\"})",
       "legendFormat": "{{pod_name}}  used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{pod_name=~\"[[pod_name]]\", area=\"nonheap\"})",
       "legendFormat": "{{pod_name}}  committed"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\", area=\"nonheap\"})",
       "legendFormat": "{{pod_name}}  max"
      }
     ]
    },
    {
     "title": "JVM Total (AVG)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\"})",
       "legendFormat": "{{pod_name}}  used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{pod_name=~\"[[pod_name]]\"})",
       "legendFormat": "{{pod_name}}  committed"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\"})",
       "legendFormat": "{{pod_name}}  max"
      }
     ]
    },
    {
     "title": "JVM Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_memory_rss_bytes{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  rss"
      },
      {
       "expr": "process_memory_swap_bytes{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  swap"
      },
      {
       "expr": "process_memory_rss_bytes{pod_name=~\"[[pod_name]]\"} + process_memory_swap_bytes{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  total"
      }
     ]
    },
    {
     "title": "JVM Heap (SUM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", area=\"heap\"})",
       "legendFormat": "{{pod_name}}  used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod_name=~\"[[pod_name]]\", area=\"heap\"})",
       "legendFormat": "{{pod_name}}  committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\", area=\"heap\"})",
       "legendFormat": "{{pod_name}}  max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap (SUM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\", area=\"nonheap\"})",
       "legendFormat": "{{pod_name}}  used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod_name=~\"[[pod_name]]\", area=\"nonheap\"})",
       "legendFormat": "{{pod_name}}  committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\", area=\"nonheap\"})",
       "legendFormat": "{{pod_name}}  max"
      }
     ]
    },
    {
     "title": "JVM Total (SUM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod_name=~\"[[pod_name]]\"})",
       "legendFormat": "{{pod_name}}  used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod_name=~\"[[pod_name]]\"})",
       "legendFormat": "{{pod_name}}  committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod_name=~\"[[pod_name]]\"})",
       "legendFormat": "{{pod_name}}  max"
      }
     ]
    },
    {
     "title": "JVM Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_memory_rss_bytes{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  rss"
      },
      {
       "expr": "process_memory_swap_bytes{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  swap"
      },
      {
       "expr": "process_memory_rss_bytes{pod_name=~\"[[pod_name]]\"} + process_memory_swap_bytes{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  total"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  system"
      },
      {
       "expr": "process_cpu_usage{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{pod_name=~\"[[pod_name]]\"}[15m])",
       "legendFormat": "{{pod_name}}  process-15m"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  system-1m"
      },
      {
       "expr": "system_cpu_count{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  cpus"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live_threads{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  live"
      },
      {
       "expr": "jvm_threads_daemon_threads{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  peak"
      },
      {
       "expr": "process_threads{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}} process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}} {{state}}"
      }
     ]
    },
    {
     "title": "GC Pressure",
     "type": "graph",
     "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{pod_name=~\"[[pod_name]]\"}[1m])) by ( pod_name) / on(application, pod_name) system_cpu_count",
       "legendFormat": "{{pod_name}} CPU time spent on GC"
      }
     ]
    },
    {
     "title": "Log Events",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{pod_name=~\"[[pod_name]]\"}[1m])",
       "legendFormat": "{{pod_name}} {{level}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_files_open_files{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  open"
      },
      {
       "expr": "process_files_max_files{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  max"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  loaded"
      }
     ]
    },
    {
     "title": "Class delta",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{pod_name=~\"[[pod_name]]\"}[1m])",
       "legendFormat": "{{pod_name}}  delta-1m"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_buffer_pool",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "repeat": "jvm_buffer_pool",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "{{pod_name}}  used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{pod_name=~\"[[pod_name]]\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "{{pod_name}}  capacity"
      },
      {
       "expr": "jvm_buffer_count_buffers{pod_name=~\"[[pod_name]]\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "{{pod_name}}  buffers"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{pod_name=~\"[[pod_name]]\"}[1m]))",
       "legendFormat": "{{pod_name}}  HTTP"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{pod_name=~\"[[pod_name]]\", status=~\"5..\"}[1m]))",
       "legendFormat": "{{pod_name}}  HTTP - 5xx"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{pod_name=~\"[[pod_name]]\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{pod_name=~\"[[pod_name]]\", status!~\"5..\"}[1m]))",
       "legendFormat": "{{pod_name}}  HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{pod_name=~\"[[pod_name]]\", status!~\"5..\"})",
       "legendFormat": "{{pod_name}}  HTTP - MAX"
      }
     ]
    },
    {
     "title": "Utilisation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_busy_threads{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  TOMCAT - BSY"
      },
      {
       "expr": "tomcat_threads_current_threads{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  TOMCAT - CUR"
      },
      {
       "expr": "tomcat_threads_config_max_threads{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  TOMCAT - MAX"
      },
      {
       "expr": "jetty_threads_busy{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  JETTY - BSY"
      },
      {
       "expr": "jetty_threads_current{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  JETTY - CUR"
      },
      {
       "expr": "jetty_threads_config_max{pod_name=~\"[[pod_name]]\"}",
       "legendFormat": "{{pod_name}}  JETTY - MAX"
      }
     ]
    }
   ]
  }
 ]
}