#!/bin/bash

#  shell config
function predefine_dir() {
  if [[ ${HOME} == "/Users/sunyindong" ]]; then
    syd_dir="$HOME"  # mac
  else
    syd_dir="${HOME}/sunyindong.syd"
  fi
  mkdir -p ${syd_dir}/codespace
  mkdir -p ${syd_dir}/codespace/tool
}
predefine_dir

export LEARN_PROJECT="${syd_dir}/codespace/learn"
mybashrc="${syd_dir}/codespace/learn/1env_install/new_machine/mybashrc"
alias mysource="source ${mybashrc}"
alias vibashrc="vi ${mybashrc}"

alias cdsyd="cd ${syd_dir}/"
alias cdcode="cd ${syd_dir}/codespace/"
alias cdtool="cd ${syd_dir}/tool/"
alias cdlearn="cd ${LEARN_PROJECT}"

# git config
alias gst="git status "
alias ga="git add "
alias gcm="git commit -m "
alias gcam="git commit --amend "
alias gco="git checkout "
alias gbr="git branch "
alias gl="git log "
alias gr="git restore "
alias gd="git diff "

# vim
alias vi="nvim "
alias vim="nvim "



